FORMS_FOLDER = "ui/"
MAIN_WINDOW_FORM = "f_main.ui"
EVENT_LIST_FORM = "f_eventlist.ui"
EVENT_EDITOR_FORM = "f_eventeditor.ui"
TYPE_SEPARATOR = " : "

#MAIN_WINDOW_WIDTH = 800 
#MAIN_WINDOW_HEIGHT = 600
MAIN_WINDOW_TITLE = "Forget-Me-Not version 0.1"

#EVENT_LIST_WINDOW_WIDTH = 400
#EVENT_LIST_WINDOW_HEIGHT = 300
EVENT_LIST_WINDOW_TITLE = "Список событий"

#EVENT_EDITOR_WINDOW_WIDTH = 500
#EVENT_EDITOR_WINDOW_HEIGHT = 200
EVENT_LIST_WINDOW_TITLE = "Редактор событий"

EVENT_MONTH_PERIOD = 1
EVENT_YEAR_PERIOD = 2
EVENT_ONE_SHOT = 3

DATE_FROM = "date_from"
DATE_TO = "date_to"
